cattle-aws:
   request_spot_instances: false
   spot_price: # spot instance pricing. Ex. "0.75" 
   cloudwatch_monitoring: false
   root_disk_size: 20
   iam_instance_profile_name:
   iam_instance_profile_worker: # specify if overlap_cp_etcd_worker is false and existing_vpc is true
   rancher_cluster_name: "cattle-aws-cluster"
   rancher_api_url: "https://rancher.xyz.com/v3"
   rancher_access_key:
   rancher_secret_key:
   rke_network_plugin: "canal"
   region: "eu-central-1"
   existing_vpc: "false"
   zone: "eu-central-1a"
   vpc_id:
   vpc_cidr_block: "10.0.0.0/16"
   subnet_id:
   security_group_name:
   ami_id: "test123"
   controlplane_instance_type: "t2.medium"
   worker_instance_type: "t2.large"
   overlap_cp_etcd_worker: "false"
   overlap_node_pool:
      hostname_prefix:
      quantity:
   master_node_pool:
      hostname_prefix: "cattle-aws-master"
      quantity: 1
   worker_node_pool:
      hostname_prefix: "cattle-aws-worker"
      quantity: 1
